---
  # After running the playbook, create a port forwarding rule to access prometheus server on localhost
  # 127.0.0.1:9090 => [guest_vm_ip]:9090
  # On the prometheus server, execute the following expressions to gather ubuntu server details
  #    - node_cpu
  #    - node_disk_bytes_read
  #    - node_filesystem_avail_bytes
  #    - node_network_receive_bytes

- hosts: node1
  gather_facts: false
  become: true
  tasks:

   - name: create users for prometheus and node_exporter
     user:
      name: "{{ item }}" 
      shell: /bin/false
      create_home: no
     with_items:
      - prometheus
      - node_exporter

   - name: create directories
     file:
      path: "{{ item }}"
      state: directory
      owner: prometheus
      group: prometheus
      recurse: yes
     with_items:
      - /etc/prometheus
      - /var/lib/prometheus

   - name: download and extract prometheus
     unarchive:
      src: https://github.com/prometheus/prometheus/releases/download/v2.0.0/prometheus-2.0.0.linux-amd64.tar.gz
      dest: /tmp
      remote_src: yes
      creates: /tmp/prometheus-2.0.0.linux-amd64

   - name: copy binaries
     copy:
      src: "{{ item }}"
      dest: /usr/local/bin
      owner: prometheus
      group: prometheus
      mode: 755
      remote_src: yes
     with_items:
      - /tmp/prometheus-2.0.0.linux-amd64/prometheus
      - /tmp/prometheus-2.0.0.linux-amd64/promtool

   - name: copy console dir 
     command: cp -r /tmp/prometheus-2.0.0.linux-amd64/consoles /etc/prometheus

   - name: copy console_libraties dir
     command: cp -r /tmp/prometheus-2.0.0.linux-amd64/console_libraries /etc/prometheus

   - name: copy prometheus config
     copy: src=files/prometheus.yml dest=/etc/prometheus/prometheus.yml owner=prometheus group=prometheus

   - name: download and extract node_exporter
     unarchive:
      src: https://github.com/prometheus/node_exporter/releases/download/v0.15.1/node_exporter-0.15.1.linux-amd64.tar.gz
      dest: /tmp
      remote_src: yes
      creates: /tmp/node_exporter-0.15.1.linux-amd64

   - name: copy node_exporter binary
     copy:
      src: /tmp/node_exporter-0.15.1.linux-amd64/node_exporter
      dest: /usr/local/bin
      owner: node_exporter
      group: node_exporter
      mode: 755
      remote_src: yes

   - name: copy prometheus and node_exporter service file
     copy:
      src: files/{{ item }}.service
      dest: /etc/systemd/system/{{ item }}.service
      owner: "{{ item }}"
      group: "{{ item }}"
     with_items:
      - prometheus
      - node_exporter

   - name: start prometheus and node_exporter service
     systemd:
      name: "{{ item }}"
      state: started
      enabled: yes
     with_items:
      - node_exporter
      - prometheus
