---

- hosts: node1
  become: true
  vars: 
   hping_attack: false
  tasks:
   - name: playbook execution begins
     debug: msg="Test suricata play started.."
   - name: install nmap
     apt: name=nmap state=latest
   - name: perform syn flood attack
     command: "hping3 -S node2 -p 80 --flood"
     when: hping_attack

   - name: perform nmap scan
     command: nmap -sS -v -n -A node2 -T4
